//Class: Appointment
// This class represents a scheduled meeting between a patient
import java.time.LocalDate;
import java.util.TreeMap;


public class Appointment{
    //Appointment identifier generated by the system class
    private int appointmentId;

    //Stores only the appointment date
    private LocalDate date;

    //Stores appointment time
    private String time;

    //Stores reason for visiting
    private String reason;

    //Linked Patient object for this appointment
    private Patient patient;

    //Linked Doctor object assigned to the appointment
    private Doctor doctor;

    //Tracks appointment progress
    private String status;

    private TreeMap<String, Appointment> appointments;


    //Constructor
    public Appointment(int appointmentId, String time, String reason, Patient patient, Doctor doctor, LocalDate date, String status ){
        this. date = date;
        this.appointmentId = appointmentId;
        this.time = time;
        this.reason = reason;
        this.patient = patient;
        this.doctor = doctor;
        this.status = status;
    }
    //Accessor or getter methods
    public int getAppointmentId(){
        return appointmentId;
    }
    public LocalDate getDate(){
        return date;
    }
    public String getTime(){
        return time;
    }
    public String getReason(){
        return reason;
    }
    public String getStatus(){
        return status;
    }
    public Patient getPatient(){
        return patient;
    }
    public Doctor getDoctor(){
        return doctor;
    }

    //Setters or mutators
    public void setDate(LocalDate date){
        this.date = date;
    }
    public void setTime(String time){
        this.time = time;
    }
    public void setStatus(String status){
        this.status = status;
    }
    @Override
    public String toString() {
        return appointmentId + "," + date + "," + time + "," + patient.getName() + "," + doctor.getName() + "," + status;
    }

}