//Class: Doctor
//Represents a medical doctor in the system
import java.time.LocalDate;

public class Doctor extends Person {
    //Unique identifier generated by ClinicManagementSystem
    private int doctorId;

    // Stores the area of medical expertise
    private String specialisation;

    //Number of years doctor has practiced
    private int yearsOfExperience;

    //The hospital room or ward assigned to the doctor
    private String hospitalRoom;

    //Doctor's weekly availability pattern
    private String availabilitySchedule;


    //Constructor
    public Doctor(int doctorId, String name, String email, String phone, String address, String gender, LocalDate dateOfBirth, String emergencyContact, String specialisation, int yearsOfExperience, String hospitalRoom, String availabilitySchedule) {

        super(name, email, phone, address, gender, dateOfBirth, emergencyContact);

        this.doctorId = doctorId;
        this.specialisation = specialisation;
        this.yearsOfExperience = yearsOfExperience;
        this.hospitalRoom = hospitalRoom;
        this.availabilitySchedule = availabilitySchedule; // ✅ correct field assignment
    }


    //Getter or accessor methods
    //Returns the assigned id
    public int getDoctorId() {
        return doctorId;
    }
    //Returns doctor's area of expertise
    public String getSpecialisation() {
        return specialisation;
    }
    //Updates the doctor's specialisation
    public void setSpecialisation(String specialisation) {
        this.specialisation = specialisation;
    }
    //Returns number of years the doctor has practiced
    public int getYearsOfExperience() {
        return yearsOfExperience;
    }
    //Returns ward or room the doctor is assigned to
    public String getHospitalRoom() {
        return hospitalRoom;
    }
    //Updates the ward or hospital room safely
    public void setHospitalRoom(String hospitalRoom) {
        this.hospitalRoom = hospitalRoom;
    }
    //Returns weekly availability pattern
    public String getAvailabilitySchedule() {
        return availabilitySchedule;
    }

    public void setAvailabilitySchedule(String availabilitySchedule) {
        this.availabilitySchedule = availabilitySchedule;
    }
}
